### ISSUE TITLE
Umbral fungus doesn’t grow when bonemealed

### ISSUE THREAD

**Issue by ghost** [TerraformersMC/Cinderscapes#10]
Umbral fungus doesn’t grow the fungus trees when it is bonemealed

**Comment by MyraLouise** [comment]
I'm having the same issue and can't find a solution anywhere.

**Comment by gniftygnome** [comment]
It does grow.  Make sure you are growing it in the middle of a 3x3 platform of umbral nylium and there is ample space above and around (they are large).

**Comment by MyraLouise** [comment]
Thanks!!!
