### ISSUE TITLE
Crashes during launch

### ISSUE THREAD

**Issue by ElvenMusic** [TerraformersMC/Cinderscapes#100]
On adding the mod initially into my main mod list, I crashed. At first i assumed it was incompatibility with Better Nether, so I launched my game with this mod and the fabric API exclusively, I tried multiple versions of the API, started with the api before the latest one, tried updating to the latest, still crashed, then I tried one of the first ones for 1.16.3, didn't help. No crash log appears on crash, only the standard minecraft unexpected error code, exit code 0. I am using the latest version of fabric. (I assume, I updated sometime earlier today) fabric-loader-0.10.5+build.213-1.16.3     I have no further information and have not tried using an earlier version of fabric, so I have no idea if downgrading temporarily would let me run the mod.

**Comment by coderbot16** [comment]
Can you please send your latest.log file in `.minecraft/logs`? This would help a lot in diagnosing the crash.

**Comment by ElvenMusic** [comment]
https://pastebin.com/G6Crn7Wp
Just ran the mod again, I hadn't stopped playing minecraft after the crash, just made a separate folder for cinderscapes

**Comment by coderbot16** [comment]
Looks like you might have downloaded the -sources jar, try downloading the jar without the -sources suffix.

**Comment by ElvenMusic** [comment]
That appears to have worked.. but looking at the curse forge files I cannot even find a sources jar file, so i have no idea how it happened. Downloading the latest version appears to have worked in starting the game up.. was one of the files accidentally uploaded with source jar instead? regardless issue cleared, able to start up the game

**Comment by coderbot16** [comment]
We used to publish the sources jar but have stopped and have removed the uploaded sources jars for this exact reason. It looks like you just downloaded it before we did all of that!

**Comment by ElvenMusic** [comment]
I had the same issue with another mod, but on redownloading that mod i saw that there was a source jar and a regular jar.. when i tried looking for different versions with this, all I saw was that I had the latest version, but i hadn't thought to look at the file extensions and there wasn't a source jar file to see and realize i had downloaded the wrong file.. rip poor timing/being unobservant lol

**Comment by ElvenMusic** [comment]
Never mind, appears to just be being unobservant, saw the closed issue you made to remove it from curse forge, so it was probably still there when I tried fixing my issue
