### ISSUE TITLE
Remove sources jar from CurseForge

### ISSUE THREAD

**Issue by coderbot16** [TerraformersMC/Cinderscapes#101]
People download this by accident and then their game crashes.

**Comment by ghost** [comment]
I approve, I'm gonna need an intellectual to dive into the gradle depths however :P

**Comment by coderbot16** [comment]
Seems like you just delete these two lines:

```groovy
        addArtifact sourcesJar
        additionalArtifacts.forEach { artifact -> artifact.displayName = "$project.project_name v$project.mod_version for $project.minecraft_version"}
```

However the existing sources jars on CurseForge need to be removed as well using the "Archive" button.

**Comment by ghost** [comment]
Aight seems simple enough
