### ISSUE TITLE
Boats?

### ISSUE THREAD

**Issue by Asmidus** [TerraformersMC/Cinderscapes#104]
If this is intentional then go ahead and close it but shouldn't the new wood types have boats? Or at least make a vanilla oak boat or something if I use planks to try and make a boat?

**Comment by NeusFear** [comment]
From what I understand these aren't really wood types perse. However, if there are boats for the vanilla mushroom things in the nether then yes this should be added.

**Comment by ghost** [comment]
Yeah the vanilla nylium types don't have boats so the Cinderscapes nylium also don't have boats.
