### ISSUE TITLE
Compatibility with Sandwichable

### ISSUE THREAD

**Issue by saltyseadoggo** [TerraformersMC/Cinderscapes#107]
Sandwichable is a lovely mod made by FoundationGames that adds many new food items and blocks to process them all centered around making custom sandwiches. One of the things Sandwichable adds are _cutting boards_ for all eight of the vanilla wood types. I would love to see this mod's wood types be able to be made into their own cutting boards to match these if Sandwichable is installed, if this endeavor would interest you.~

**Comment by ghost** [comment]
I think it sounds like a great idea, but ultimately I think compatibility would make more sense being contained inside of Sandwichable and not Cinderscapes. (Then they can also do compatibility for other biome mods, maybe the other Terraformers mods). So maybe we open an issue over at https://github.com/FoundationGames/Sandwichable for this.

**Comment by saltyseadoggo** [comment]
So it shall be. Would you like to make the report, or would you like me to?

**Comment by saltyseadoggo** [comment]
I apologise if that sounded presumptuous; I gleaned your response as meaning that you wanted to open the issue yourself. I've opened the issue on Sandwichable's page for all three TerraformersMC projects (as well as Tech Reborn and BetterNether).~

**Comment by ghost** [comment]
No that's alright, I've been absent the past couple days otherwise I would've done it, but it doesn't really matter.
