### ISSUE TITLE
Cinderscapes and Astromine: Complete causes vanilla items to disappear from creative inventory tabs.

### ISSUE THREAD

**Issue by K0-RR** [TerraformersMC/Cinderscapes#109]
When Cinderscapes and Astromine are both loaded then creative inventory tabs are lacking items from vanilla Minecraft.

1.16.4; fabric api 0.25.4; fabric loader 0.10.6

Reported to Mixinors - https://github.com/Mixinors/Astromine/issues/352

**Comment by NeusFear** [comment]
Astromine needs to update CCA

**Comment by ghost** [comment]
I reported this issue to the Astromine team a couple week ago, at this point the ball is in their court.
