### ISSUE TITLE
Enhancement: Soul Glass

### ISSUE THREAD

**Issue by saltyseadoggo** [TerraformersMC/Cinderscapes#114]
Inspired by dranorter's suggestions for entirely new gameplay features that are exclusive to the Nether, I thought that I would share one I had some time ago. **Soul Glass** would be a variant of glass crafted from soul sand with the unique property that it could be **passed through by certain entities under certain circumstances**. I had a few ideas on how this could work...
- Entities wearing **Soul Speed boots** could pass through the glass; all other entities could not. This would function as a simple way of creating a player-only door, or a wall that is non-solid to players for applications in mob farming, and would tie into the Soul Speed enchantment as well. It would also act as a way of stopping ender pearls from being thrown through an area.
- Entities moving **below a certain speed** could pass through the glass; entities moving too quickly could not. This would function like a non-Newtonian fluid, albeit solid, and could allow for anti-elytra gates, fall damage traps that let the killed entity's drops fall through, or even limiting a player's speed to walking and not sprinting when desirable.
- Entities moving **above a certain speed** could pass through the glass; entities moving too slowly could not. Build opportunities would include gates that can only be passed through with elytra or ender pearls, or floors that can be walked over normally or passed through by falling from a great height.

Ideally, the soul glass would be a deep brown in colour to match the soul sand used to create it. Because of it being a different colour by default,**stained soul glass would have terracotta colours** as opposed to the regular dye colours, opening up more glass colours for players to build with.~

Let me know what you think, and, of course, close the issue if you don't care for this idea. It's all up for discussion, and is just a humble idea.~

**Comment by saltyseadoggo** [comment]
I realise now that this may be out of scope for *a biome mod.* Silly me.

**Comment by Angular-Angel** [comment]
Maybe add an item that can be used to enable it? If TerraformersMC wants more tech options from their biomes, this is an option.

**Comment by ghost** [comment]
This is a good idea. I agree it might be out of the scope of a biome mod, but I might steal this for something else :eyes:

**Comment by ghost** [comment]
I'm closing this because I think the idea is out of scope for this project, but it's something I implemented a version of in [Vaerian/Unbound](https://github.com/Vaerian/Unbound/).
