### ISSUE TITLE
Creative inventory bug

### ISSUE THREAD

**Issue by SconeStone** [TerraformersMC/Cinderscapes#117]
When I go into creative mode and open my inventory only modded items show up in all tabs, I don't know if this is a compatibility issue with another mod but thought it well to metion (this is v.1.2.4).
![2020-12-02_19 06 31](https://user-images.githubusercontent.com/74540562/100913233-c69e3b80-34d1-11eb-9b6c-8780633c212e.png)

**Comment by Prospector** [comment]
> When I go into creative mode and open my inventory only modded items show up in all tabs

I'm not sure what you mean by this. Everything in your screenshot looks correct. If you're referring to Cinderscapes blocks being in the Building Blocks tab, that is intentional.

**Comment by ghost** [comment]
The problem is Cardinal Components. Some mod that you installed uses an outdated version of Cardinal Components, so downloading the newest version and putting it into the mods folder should solve the problem.

See #109 #95 and #91
