### ISSUE TITLE
A number of tags are missing

### ISSUE THREAD

**Issue by SabSparrow** [TerraformersMC/Cinderscapes#12]
The data/minecraft/tags/blocks and data/minecraft/tags/items folder are missing a number of tags for the new wart, quartz and wood blocks
The blocks folder lacks wall_signs, standing_signs, stairs, slabs, planks, non_flammable_wood, logs, wart_blocks.
The items folder lacks wooden_trapdoors, wooden_stairs, wooden_slabs, wooden_pressure_plates, wooden_fences, wooden_doors, wooden_buttons, stairs, slabs, planks, non_flammable_wood, logs
Quartz blocks should be added to stairs.json and slabs.json
Umbral and Scorched stuff should be added to the others
Oh, and Umbral Nylium and Umbral Fungus should probably be added to enderman_holdable, to match other Nyliums and Fungi

**Comment by ghost** [comment]
Closed by #14 in ffd1b05
