### ISSUE TITLE
Cinderscapes crashing

### ISSUE THREAD

**Issue by Grithz** [TerraformersMC/Cinderscapes#121]
[https://i.hizliresim.com/PQVreG.png](https://i.hizliresim.com/PQVreG.png)

It is the only mod in the instance.

**Comment by Grithz** [comment]
I did redownload it.

**Comment by Grithz** [comment]
The instance also has Fabric API.

**Comment by Prospector** [comment]
Weird, can you try downloading it again with the latest version to see if it's still happening?
