### ISSUE TITLE
Using Fabric API to add to villager trades, removes all trades from mods not using the api.

### ISSUE THREAD

**Issue by dandin87** [TerraformersMC/Cinderscapes#129]
Using Fabric API to add to villager trades, removes all trades from mods not using the api. In addition adding to villager trades with fabric api will duplicate all trades every time another trade is added as explained here, https://github.com/FabricMC/fabric/issues/1427

Repurposed Structures has removed their usage of the api, and I was hoping Cinderscapes could either add the trades without using fabric API, or simply remove them until this is fixed. Currently this is breaking custom villager trades from Sandwichable and Charm in All of Fabric 3.

**Comment by TelepathicGrunt** [comment]
@haykam821 the api is broken and nuke everyone else's trades as well. Do not thumbs down this issue as it is a major problem. I would encourage everyone to remove their usage of that api until it is fixed to maximize mod compatibility and prevent trade duplications (such as villagers showing two leads for trade on the same trade level which looks wack af)

**Comment by TelepathicGrunt** [comment]
For cinderscapes, here's the new method I am using which adds the trade directly into the villager's trades. this should be super easy to switch to:  https://hatebin.com/egqtpgobno

**Comment by haykam821** [comment]
This issue is fixed by FabricMC/fabric#1430.

**Comment by dandin87** [comment]
Fixed in FAPI with no update being required by mods. 
> This issue is fixed by [FabricMC/fabric#1430](https://github.com/FabricMC/fabric/pull/1430).
