### ISSUE TITLE
World gen bug??

### ISSUE THREAD

**Issue by YerDatsRight** [TerraformersMC/Cinderscapes#131]
we decided to update our modpack with some extra mods and biomes from Cinderscapes seemed to be glitching out, causing these random chunks of floating crystals, random chunks of quartz pillars, etc. apon joining the server again it seemed out into the overworld and is effecting other biomes from your mods, also glitching them out.

https://gyazo.com/eb24bc42d47753df09cb3eeceae73c4b
![Nether 1](https://user-images.githubusercontent.com/82824629/119651828-bce60700-be68-11eb-9cb6-5845e409c239.png)
![Overworld 1](https://user-images.githubusercontent.com/82824629/119651838-bfe0f780-be68-11eb-99b1-f0d4aa4e9130.png)

**Comment by coderbot16** [comment]
This is caused by having different mods on the server than what you have on the client. Currently Fabric has no server/client mod list validation, so you get things like this. Make sure you have the same mods on both sides.
