### ISSUE TITLE
Could not play on servers with no mods with Cinderscapes-installed client

### ISSUE THREAD

**Issue by l2dy** [TerraformersMC/Cinderscapes#150]
Entity mapping is not matching.

**Expected behavior**: Modded client can be used to play on unmodded servers.

**Server version**: fabric-server-mc.1.19.4-loader.0.14.19-launcher.0.11.2.jar with no mods.

**Client version**: fabric 0.14.19 with Cinderscapes 3.2.0 and fabric-api 0.81.0+1.19.4.

**Screenshots**:
With Cinderscapes enabled

![2023-05-15_20 40 33](https://github.com/TerraformersMC/Cinderscapes/assets/14329097/dfb548f0-9f53-44fc-9e30-2b97ab15870a)

With Cinderscapes disabled

![2023-05-15_20 41 12](https://github.com/TerraformersMC/Cinderscapes/assets/14329097/80c36dbb-8202-4d68-959f-538b90b77f4d)

**Comment by gniftygnome** [comment]
As a biome mod, Cinderscapes adds all kinds of things to the game registry.  It has to be installed on both sides in order for those things to work.  I am baffled as to what you are trying to do by running the mod only on the client?

**Comment by l2dy** [comment]
I play both on my own servers with biome mods and public servers without them. Keeping the compatibility with vanilla servers allows me to maintain a single set of mods on client-side and did work in previous versions of Cinderscapes.

This is something good to have but not a must for me, so if the incompatibility is intended, I'm OK with that.

**Comment by gniftygnome** [comment]
Now I understand how you expected it to work.  That was never intentional functionality; it's just how things worked when when mods were mismatched between client and server.  We did not add anything new to prevent it, but I think what you are seeing is a new feature of Fabric.

**Comment by l2dy** [comment]
Understood. Thanks for explaining!
