### ISSUE TITLE
Missmatching blocks on vanilla servers

### ISSUE THREAD

**Issue by kittech0** [TerraformersMC/Cinderscapes#153]
Basically the mod breaks blocks on vanilla servers.
This bug can be found in multiple mods like: traverse, dawn api, cinderscapes, blockus, terrestria

**Comment by kittech0** [comment]
look at https://github.com/Brandcraf06/Blockus/issues/301

**Comment by gniftygnome** [comment]
It is a fundamental requirement of any mod that adds blocks the blocks must be added on the server side.  Some mods can sync their content to the client, but no mod that adds blocks will work without being installed on the server.
