### ISSUE TITLE
Ash particles cause performance issues in the ashy shoals biome

### ISSUE THREAD

**Issue by haykam821** [TerraformersMC/Cinderscapes#160]
The probability for ash particles in the ashy shoals biome is 0.675, which is significantly higher than the approximately 0.118 probability of the basalt deltas biome. The amount should be reduced, either by default or via configuration, to allow people with performance issues to play at a stabler frame rate. Note that minimal particles turns off all biome particles.

**Comment by gniftygnome** [comment]
This was addressed in #42 by adding a config option to disable ash fall.  Is there really more needed beyond that?

**Comment by haykam821** [comment]
That issue was regarding the placement of ash blocks. The `enableAshFall` configuration option added as a result of that issue doesn't impact whether particles are spawned, which seems to have a larger performance impact.

**Comment by gniftygnome** [comment]
I'm adding a config option to the next release of Cinderscapes which when enabled will limit the probability of all instances of biome ash particles to 0.125.  This is easy to do (whereas limiting it just for Cinderscapes is not).

**Comment by gniftygnome** [comment]
Done in 5.0.0-beta.2.
