### ISSUE TITLE
Mod compat issue?

### ISSUE THREAD

**Issue by contrarybaton60** [TerraformersMC/Cinderscapes#164]
hey, I'm trying to update a modpack to 1.20.6, but the game crashes. I know it's because of Cinderscapes, but I don't know why, and wondering on how to fix the issue.

https://mclo.gs/5pTXVlb

**Comment by contrarybaton60** [comment]
Nevermind, adding the Satin API mod solves the issue for whatever reason.

**Comment by gniftygnome** [comment]
At a guess, maybe some other mod in the pack includes an older version of Satin API.  The crash that fingered Cinderscapes was actually in Satin API code...

**Comment by gniftygnome** [comment]
BTW it is super cool to see somebody using Traverse's Modern Beta functionality...

**Comment by contrarybaton60** [comment]
It kinda does work but also doesn't, *Moderner* Beta (a fork of modern beta for new versions) have presets like "Hybrid Beta" and "Hybrid Release" which uses the terrain generation from an old version while also adding back vanilla biomes. I know Traverse and Cinderscapes will work fine but I can't remember.

here's the modpack if you want to check out: https://modrinth.com/modpack/williams-console

**Comment by contrarybaton60** [comment]
Alright, it does work!
![2024-06-15_21 23 16](https://github.com/TerraformersMC/Cinderscapes/assets/110365948/f2b1fb1f-4949-4fc8-9e53-782a8b39e595)
![2024-06-15_21 25 17](https://github.com/TerraformersMC/Cinderscapes/assets/110365948/56661c3e-92a2-4789-8fb9-cb996207f7db)

**Comment by gniftygnome** [comment]
Yeah I just checked it out and was going to say, looks like everything is working as intended!  Man it's been a while since I played Minecraft on the console...
