### ISSUE TITLE
Crash upon startup. Was fixed when cinderscapes was removed.

### ISSUE THREAD

**Issue by HacoKavanah** [TerraformersMC/Cinderscapes#165]
[crash-2024-07-04_18.21.41-client.txt](https://github.com/user-attachments/files/16100786/crash-2024-07-04_18.21.41-client.txt)

**Comment by gniftygnome** [comment]
The stack trace does not say anything about Cinderscapes.  Could you try removing vanillafix?  It *is* in the crash report, and if it is not what is crashing, I suspect it is responsible for eliding a more useful stack trace.

**Comment by HacoKavanah** [comment]
[crash-2024-07-04_23.28.56-client.txt](https://github.com/user-attachments/files/16102709/crash-2024-07-04_23.28.56-client.txt)

**Comment by gniftygnome** [comment]
This does not reproduce with just Cinderscapes, so there must be some interaction with another mod.  However, there was some sketchy code involved in the stack trace.  I have improved it and released Cinderscapes 5.0.1.  Please try it and let me know whether it resolves the crash.

**Comment by HacoKavanah** [comment]
It works now! Thanks! <3
