### ISSUE TITLE
Problem with leaves

### ISSUE THREAD

**Issue by JavieseN** [TerraformersMC/Cinderscapes#24]
All the leaves of the overword start to disappear when I start a world.
I don't know if it could be some kind of incompatibility with other mods.
Thx.

**Comment by NeusFear** [comment]
Are you in dev?

**Comment by coderbot16** [comment]
Is this only with Terrestria, or do you have other mods loaded? This sounds like an issue that has recently been affecting Jumploader.

**Comment by ghost** [comment]
[TerraformersMC/Terrestria#157](https://github.com/TerraformersMC/Terrestria/issues/157)

This is a jump loader issue, I hope it’ll be fixed soon. I believe the conclusion we came to was that Jump loader does work with MultiMC but not the twitch client?

**Comment by ghost** [comment]
I just opened an official issue in jumploader so check there for status updates. comp500/Jumploader#5
