### ISSUE TITLE
BiomeAccessor Crash

### ISSUE THREAD

**Issue by JoshMayberry** [TerraformersMC/Cinderscapes#39]
If I try using the latest version (cinderscapes-1.0.7+build.43-1.16.1-sources.jar), I get the following crash:
`'com.terraformersmc.cinderscapes.mixin.BiomeAccessor' was not found`.

Here is the entire log file: [logs.txt](https://github.com/TerraformersMC/Cinderscapes/files/4978196/logs.txt)

**Comment by NeusFear** [comment]
you need to use the actual jar, not the sources jar
