### ISSUE TITLE
Zoglin spawning in mid air

### ISSUE THREAD

**Issue by ghost** [TerraformersMC/Cinderscapes#48]
The vanilla spawning algorithm apparently spawns zoglins in mid air. This sounds like a vanilla bug but follow up on it

**Comment by ghost** [comment]
I wonder if this is still an issue

**Comment by coderbot16** [comment]
This is still an issue in the current 1.16.3 version:
![image](https://user-images.githubusercontent.com/22420959/97773088-3c496d00-1b0a-11eb-8c55-ae26b9632644.png)
