### ISSUE TITLE
Amount of fire resistance gained from bramble berries is severely imbalanced

### ISSUE THREAD

**Issue by Ookidablobida** [TerraformersMC/Cinderscapes#51]
I think that a guaranteed 2:00 of fire resistance from such an easy to obtain item is unfair and should be balanced. I was thinking that it could be the same as hunger from rotten flesh (an 80% chance of getting it for 30 seconds). This is so that instead of simply being an easy source of lots of fire resistance, it could be more of a last minute life-saving thing.

**Comment by NeusFear** [comment]
Agreed.
