### ISSUE TITLE
Polypite Quartz variants have strange culling issues; may be a Sodium incompatibility

### ISSUE THREAD

**Issue by saltyseadoggo** [TerraformersMC/Cinderscapes#55]
Polypite Quartz variants (regular, Rose, Smoky and Sulfur) seem to prevent parts of themselves from drawing if viewed through the invisible parts of the parts closest to the camera. This creates ugly graphical bugs when looking at them, as not all of them show when they're supposed to, and they can even hide entire Polypite Quartzes behind them.
Sodium was used when testing this, so this may be a compatibility issue with Sodium's renderer.

![2020-08-16_16 05 26](https://user-images.githubusercontent.com/69029346/90346211-1537d080-dfdc-11ea-88a7-976ed2a2d77a.png)
![2020-08-16_16 05 35](https://user-images.githubusercontent.com/69029346/90346216-1bc64800-dfdc-11ea-8a47-6a1be2dbe244.png)
![2020-08-16_16 05 38](https://user-images.githubusercontent.com/69029346/90346218-1cf77500-dfdc-11ea-99bc-345516fb2388.png)
![2020-08-16_16 05 44](https://user-images.githubusercontent.com/69029346/90346219-1ec13880-dfdc-11ea-9735-a909d0ed785b.png)
![2020-08-16_16 08 26](https://user-images.githubusercontent.com/69029346/90346221-208afc00-dfdc-11ea-8412-f18ebc5af028.png)
![2020-08-16_16 09 05](https://user-images.githubusercontent.com/69029346/90346223-22ed5600-dfdc-11ea-931d-1567bb9c79b8.png)
![2020-08-16_16 09 18](https://user-images.githubusercontent.com/69029346/90346225-254fb000-dfdc-11ea-8e59-fc6fecf31336.png)
![2020-08-16_16 09 48](https://user-images.githubusercontent.com/69029346/90346226-27197380-dfdc-11ea-9eb0-8ce11d04e89b.png)
![2020-08-16_16 09 56](https://user-images.githubusercontent.com/69029346/90346227-297bcd80-dfdc-11ea-8098-d84562d8fa5f.png)
![2020-08-16_16 14 19](https://user-images.githubusercontent.com/69029346/90346229-2bde2780-dfdc-11ea-9088-0d8b64f34a36.png)

**Comment by ghost** [comment]
I believe this is actually a vanilla issue, that's just how vanilla chooses to render overlapping semi-transparent layers. If you change your graphics setting from "Fancy" to "_Fabulous!_" it might fix the rendering depending on your graphics hardware. It's not as noticeable on the vanilla coral because it takes up more of the block space, but I believe it's also plagued by the same issue. If I'm wrong I'll be happy to take a look at it, but I believe that was the consensus we came to.

**Comment by Prospector** [comment]
one way we could fix this would be to make the shape of the model exactly match the texture, which would be a pain for resource pack authors but it *would* work

**Comment by saltyseadoggo** [comment]
Hmm... Would moving them to the 'Cutout' render layer fix it, or are they already in it? I'm trying to think. Plants that use block_cross as a model don't have this issue, so there must be something that applies to their rendering that one could apply to them, instead of using the coral fan render attributes as they are.

**Comment by saltyseadoggo** [comment]
I just checked the coral fans, and this issue doesn't seem to apply to them as of 1.16.1.
![2020-08-16_17 00 04](https://user-images.githubusercontent.com/69029346/90346956-005e3b80-dfe2-11ea-9921-ae61d325538b.png)
Edit 1: screenshot
Edit 2: screenshot that doesn't have potion particles in it

**Comment by Prospector** [comment]
the problem is that they're not just a cutout, they're also translucent. There's not like a translucent cutout render layer afaik

**Comment by saltyseadoggo** [comment]
Oh, are they semi-transparent? That would differ from the corals, yes. Hmm...
I had thought that they were opaque, seeing them in the game. Are they supposed to be semi-transparent, like stained glass?

**Comment by Prospector** [comment]
Hmm, I think they are supposed to be. But maybe not...hmm

**Comment by saltyseadoggo** [comment]
I also tested _Fabulous!_ graphics as per Vaerian's suggestion, to no avail, but I only have an Intel to test on...

**Comment by NeusFear** [comment]
Maybe they were translucent before I retextured them, they can be moved to cutout now I suppose. Unless I need to make them translucent again

**Comment by Angular-Angel** [comment]
I'm having a similar issue with said quartz when next to the larger quartz blocks, see:

![2020-10-11_00 59 13](https://user-images.githubusercontent.com/938571/95672333-28d76180-0b5d-11eb-8788-c4e3f93d8e0c.png)

**Comment by Angular-Angel** [comment]
It's hard to see on github cause it's all black, but when you look at the screenshot on it's own you can see the polypite screwing with the crystal behind it.
