### ISSUE TITLE
Polypite Quartz duplication

### ISSUE THREAD

**Issue by saltyseadoggo** [TerraformersMC/Cinderscapes#56]
Moving a Slime Block with Polypite Quartz crystals of any variant attached will drop the respective quartz items for the polypite crystals whilst keeping the polypite crystals attached, allowing for duplication. This behaviour is shared with the Coral Fans in the vanilla game, but the fans drop nothing without Silk Touch, preventing this issue.
I don't expect you to personally resolve this base game bug, but having the Polypite Quartz crystals drop nothing when broken without Silk Touch could be a solution to the duping, and a potential means of crafting them into their respective quartz items could allow for the same means of obtaining quartz items. See what you can some up with, of course.

**Comment by saltyseadoggo** [comment]
It would be a non-conventional solution in that it would use hard-coded functions instead of a loot table, but could you remove the polypite quartz variants' loot tables, and instead hard code them to drop their items when broken by a player only, so being moved by a piston wouldn't let them drop anything? This would also mean that explosions would never let them drop their items.

**Comment by saltyseadoggo** [comment]
Of course, this workaround would be best removed once piston duplication is fixed. I have heard a rumour that Mojang is keeping it in for the time being to allow for TNT duplication and its associated farms to continue, a feature that Mojang has supported by making TNT drop every block that it breaks.

**Comment by ghost** [comment]
That might be a good idea. I also know that it seems the same type of duplication glitch is currently possible with the amethyst in 1.17 so I might wait and see if Mojang patches that to see if it'll cascade into the polypite quartz as well.

**Comment by ghost** [comment]
Fixed in 1.17 dev
