### ISSUE TITLE
1.16.3 is out. Please update. Thanks. <3

### ISSUE THREAD

**Issue by MagmaSlime123** [TerraformersMC/Cinderscapes#60]

**Comment by MagmaSlime123** [comment]
Ignoring wont help.

**Comment by NeusFear** [comment]
We know. It's a lot of work. Be patient. <3

**Comment by tazz4843** [comment]
Opening bug reports in every single one of Terraformers's repos doesn't remotely help and if anything, it hinders the development of 1.16.3 because now they have to come and close these useless reports.
Not trying to be a jerk here, just saying.

**Comment by ghost** [comment]
Hey high key dude I think you need to chill. I'm the main developer of this mod, and I get that you really care about this mod but at the end of the day life is a lot more than just mods. Trust me I hate not having the mod updated more than you do. It gives me anxiety. I'm sorry that it's been taking a while, but there was the major hurdle of getting fabric api updated, and then in the past week alone I had a close family member of mine go into the hospital, along with starting university, and a whole host of other things. The point is that we're people just like you and everyone else, and while we love modding, it is at the end of the day a hobby for us, and sometimes life gets in the way of that. You need to respect the fact that we all having friends and family members, jobs and school, other life obligations, and sometimes this needs to take the back seat. We're working as hard as we can to get this update out, but we just need some compassion and understanding. Spamming us is not going to make it go any faster, if anything it's going to frustrate us even more.
