### ISSUE TITLE
Nether Quartz Tools?

### ISSUE THREAD

**Issue by Angular-Angel** [TerraformersMC/Cinderscapes#61]
For nether survival runs, some nether quartz tools would be really handy. Give them the same mining level as stone tools, terrible durability, Iron comparable mining speed, damage, attack speed, and enchantability, say, and I think they'd have a decent niche in both nether and classic survival. I'm not entirely sure it's in keeping with the theme of the mod, but it's not too far off, either.

**Comment by Angular-Angel** [comment]
If you want to get really crazy, you could allow nether quartz to substitute for feathers when making arrows? It would allow actually making feathers in the nether, and explain how pigmen make their arrows. XD

**Comment by NeusFear** [comment]
I preferred your idea of the rusty stuff as a substitute for iron or a way of getting iron, a new type of stone tool doesn't really seem like something we would add since those are already possible

**Comment by Angular-Angel** [comment]
True, but as described quartz tools would be significantly different from stone, in a way that I think makes them interesting. Especially with how rare blackstone is.

**Comment by Angular-Angel** [comment]
Also, quartz shears would be cool. much lower durability, but better mining speed than iron shears, and slightly more enchantable, too.

**Comment by ghost** [comment]
Quartz tools doesn't exactly seem like it fits all that well inside of Cinderscapes, but I'll certainly make a mod that does the same thing and has compatibility with Cinderscapes under @CumulusMC.
