### ISSUE TITLE
Add Piglin Trades

### ISSUE THREAD

**Issue by Angular-Angel** [TerraformersMC/Cinderscapes#64]
I don't think anything from Cinderscapes shows up as a piglin trade - you might want to add the variant quartzes, at least, if nothing else.

**Comment by saltyseadoggo** [comment]
Drops from Piglin bartering are managed through loot tables, which, unfortunately, cannot be appended to with a _replace = false_ in the same way as tags. While this would be possible, it would make this mod's changes to Piglin bartering incompatible with any other mod or datapack's changes to bartering. Short of some new library that lets loot tables be appended or this mod modifying the Piglin at the code level to use a new loot table that references the old one so other mods or datapacks that override it could still work one at a time, I don't see how this would be possible whilst retaining compatibility.

**Comment by Angular-Angel** [comment]
Hmm, gotcha. That sounds like something fabric should handle, maybe? I'm pretty sure forge lets mods screw with loot tables, I find items from a variety of mods in my 1.12.2 chests.

**Comment by NeusFear** [comment]
https://fabricmc.net/wiki/tutorial:adding_to_loot_tables

**Comment by saltyseadoggo** [comment]
Well, colour me surprised.~ Forgive me; I don't know all of Fabric's features.
I don't suppose there's a way to use that same mechanic to _remove_ something from a loot table? If so, you could easily remove the vanilla quartz barter and add in one that returns one of the items in your tag c:quartz, so as to keep the same weight for dropping quartz items usable in redstone components.
