### ISSUE TITLE
More Mobs?

### ISSUE THREAD

**Issue by Angular-Angel** [TerraformersMC/Cinderscapes#67]
I don't think this mod adds any new mobs to populate it's new biomes - which is too bad, as there could definitely be some interesting additions there. Maybe some kind of lava crab, with edible eggs, that's mostly passive unless you get too close to it's nest? For bonus points, make the females huge and nest gaurding, and the males tiny and fleeing - until there's a bunch of them, at which point they go on the war path and try and swarm you. Might also have edible meat and maybe useful shells? The quartz canyon could be home to some kind of quartz elemental, like the blazes, maybe?

**Comment by NeusFear** [comment]
New mobs won't happen in this mod, we have a new mod planned when the DumbCode studio (A project that I work on with another team for animation and modeling) and it will have compatibility with these biome mods to cater to their biomes too.
