### ISSUE TITLE
Crystiniums do not compost.

### ISSUE THREAD

**Issue by Angular-Angel** [TerraformersMC/Cinderscapes#68]
I haven't tested any other plant from the mod, but I suspect few of them do either. And given that most other living stuff from the nether composts, I feel it should be possible.

**Comment by Angular-Angel** [comment]
Also, crystiniums do not respond to bone meal, either. And do they have a spread mechanic? If not,that would be a cool thing to add.

**Comment by Angular-Angel** [comment]
Though, I guess without any use other than decorative it's not super important.

**Comment by ghost** [comment]
All the code was in there I just passed the method a block instead of an item lol. I'm super good at coding, I promise.
