### ISSUE TITLE
Cave generator cannot cut through Umbral Nylium

### ISSUE THREAD

**Issue by saltyseadoggo** [TerraformersMC/Cinderscapes#69]
**Expected Behaviour**
The cave generator would be able to remove Umbral Nylium as it does the vanilla crimson and warped nylium, and all Nether blocks.
**Actual Behaviour**
The cave generator cannot remove Umbral Nylium from caves, leaving floating umbral nylium where it breaks through the surface.
**Steps to Reproduce**
* Create a new world with seed 919343044181396312 in Creative or Spectator mode with cheats enabled.
* Enter the Nether by any means, and run /teleport [player name] 308 94 439. Look around and find the nearby cave with floating umbral nylium at its surface.
**Attachments**
![2020-10-12_22 49 39](https://user-images.githubusercontent.com/69029346/95821307-89da7300-0cde-11eb-937d-9c9c2414a24f.png)

Curiously, this bug existed in early snapshots of the vanilla 1.16 update with crimson and warped nylium.~

**Comment by ghost** [comment]
Interesting I'll make sure to take a look at that. I'm guessing there's a whitelist somewhere I've just got to find
