### ISSUE TITLE
On 1.16.2 Branch Decorators are broken

### ISSUE THREAD

**Issue by ghost** [TerraformersMC/Cinderscapes#72]
Exactly what it says on the tin, some of the decorators are broken so most of the features don't generate properly.

**Comment by ghost** [comment]
Maybe @shartte can take a look at this?

**Comment by shartte** [comment]
Is this for custom decorators found in https://github.com/TerraformersMC/Cinderscapes/tree/1.16.2/src/main/java/com/terraformersmc/cinderscapes/decorator ? Or also for Vanilla decorators?

**Comment by NeusFear** [comment]
I believe only the custom ones

**Comment by shartte** [comment]
Can you give an example that doesn't generate?

I don't see anything particularly wrong with it, and some custom decorator based features seem to generate:
![image](https://user-images.githubusercontent.com/1261399/95889832-4259f280-0d83-11eb-9eda-7bd0dfdaf989.png)
(I thought these mushrooms are based on one of the custom decorators)

**Comment by NeusFear** [comment]
the current problem is in the spikes biome, the spikes arent generating but we're thinking it may be an issue with the shapes code so we're investigating that since we also confirmed that the decorators seems to be functioning

**Comment by ghost** [comment]
Yeah all of that works, but basically the features that aren't working are the blackstone shales (in their namesake biome), they kind of spawn but not in the same quantities, and the quartz spikes in the quartz whatever the hell biome.

**Comment by ghost** [comment]
Scoder says it's a problem with the generation shapes itself not the decorators, which it could be, but the shapes lib is MC independent and hasn't changed so I dunno if that's affecting it. It could be that the whitelists got messed up and stuff somewhere, but I can take a look at it if you don't find anything.

**Comment by shartte** [comment]
Hm, this is hard to debug without knowing how it *should* look ;-)

So, just placing a diamond-block column unconditionally in the ShaleFeature looks like this:

![image](https://user-images.githubusercontent.com/1261399/95892972-9a92f380-0d87-11eb-9bd6-cd6d23aecf04.png)

**Comment by NeusFear** [comment]
Here is an image of what they looked like: https://media.forgecdn.net/attachments/299/163/java_z86lfuz60h.png

**Comment by shartte** [comment]
I looked at CeilingShardFeature and it seems the shapes are always empty. 

I dont know if that's the same issue as the shales (might not be).

Overall I don't think I can help with this one as the decorators seem to be generally working at least.
