### ISSUE TITLE
Cinderscapes items are in vanilla Creative tabs and its own tab

### ISSUE THREAD

**Issue by saltyseadoggo** [TerraformersMC/Cinderscapes#73]
**Expected Behaviour**
Cinderscapes' items would only appear in Cinderscapes' Creative mode tab, not the vanilla tabs, matching the behaviour of other Fabric mods, an example being Terrestria.
**Actual Behaviour**
Cinderscapes' items appear in both the vanilla Creative mode tabs- Building Blocks, Decoration Blocks and so on- and the dedicated Cinderscapes tab.
**Steps to Reproduce**
* Create a new world in Creative mode.
* Open the inventory, and scroll to the bottom of the Building Blocks tab. Cinderscapes blocks are present.
* Click on Fabric's page change button, and switch to the Cinderscapes tab. The same Cinderscapes blocks are present here as well.
**Attachments**
![2020-10-12_23 13 08](https://user-images.githubusercontent.com/69029346/95822317-8647eb80-0ce0-11eb-8917-df218be7d7d2.png)
![2020-10-12_23 13 14](https://user-images.githubusercontent.com/69029346/95822318-87791880-0ce0-11eb-8aed-a9168d7b3840.png)

**Comment by ghost** [comment]
This is intentional, we purposefully did it this way so that the items would be in both the expected vanilla item group for their respective type of block, and in one unified tab for people looking for modded blocks. I believe it is the same way for Terrestria and Traverse

**Comment by saltyseadoggo** [comment]
I can say that it is not the same for Terrestria, having been playing with it on its latest version for quite some time. I cannot speak for Traverse.

**Comment by ghost** [comment]
Interesting, idk I just remember cloning the code from one of those initially and that's how it was being done.

**Comment by saltyseadoggo** [comment]
Times have changed, I suppose. _shrug_
