### ISSUE TITLE
Cinderscapes' Creative menu tab has a random icon each session

### ISSUE THREAD

**Issue by saltyseadoggo** [TerraformersMC/Cinderscapes#74]
**Expected Behaviour**
The Cinderscapes Creative menu tab would use one item model as its icon consistently, mirroring the behaviour of the vanilla tabs and tabs from other Fabric mods, such as Terrestria.
**Actual Behaviour**
The Cinderscapes Creative menu tab chooses a random item model from the mod to use as its icon every single time the player joins a world. Many of these items, such as the various stairs and slabs, don't make very representative icons for the mod.
**Steps to Reproduce**
* Load any world in Creative mode.
* Check the icon of the Cinderscapes tab in the Creative menu.
* Save and quit to title, then rejoin.
* Check the icon of the Cinderscapes tab in the Creative menu again.

**Comment by ghost** [comment]
This is also intended functionality, though it is changed on the 1.16.2 branch so idk take that how you will :P
