### ISSUE TITLE
Undo the undo of the TR compat :P

### ISSUE THREAD

**Issue by ghost** [TerraformersMC/Cinderscapes#76]
I'm mostly just adding this so I remember to check back up on it, but I'm sure we'll get it figured out.

**Comment by NeusFear** [comment]
lol oops

**Comment by NeusFear** [comment]
so was the package supposed to be c.tags.items or was it supposed to be c/tags/items?

**Comment by ghost** [comment]
wydm, just like the directory c/tags/items so I guess the package c.tags.items, but idk...? am confusion american explain why is this one kansas, but this one is not ar-kansas

**Comment by NeusFear** [comment]
well it wasn't in a directory format when I changed it. It was in a package format in the resources dir which was whi I considered it a bug before

**Comment by ghost** [comment]
Yeah that might've been my bad, kinda weird though
