### ISSUE TITLE
whilst trying to load the mod up The game will not launch.

### ISSUE THREAD

**Issue by Jamflof** [TerraformersMC/Cinderscapes#77]
I am not sure what is causing this, and despite originally trying to launch the game with a few more mods, launching it by itself presents the exact same problem.
i unpacked the log.gz file and have attached it to this.
[2020-10-13-3.log](https://github.com/TerraformersMC/Cinderscapes/files/5373004/2020-10-13-3.log)
I have reinstalled minecraft and tried several things, but nothing seems to be working.

**Comment by ghost** [comment]
I think you might've downloaded the sources jar from curseforge. Make sure you're using the normal binary, if you are still having a problem after that then let me know
