### ISSUE TITLE
Crashes on the dedicated server

### ISSUE THREAD

**Issue by coderbot16** [TerraformersMC/Cinderscapes#82]
`Registry#containsId` only exists on the client, so accessing it on the server crashes.

```
    @Environment(EnvType.CLIENT)
    public abstract boolean containsId(Identifier id);
```

It looks like the place where this is used is just sanity checking code:

https://github.com/TerraformersMC/Cinderscapes/blob/1.16.2/src/main/java/com/terraformersmc/cinderscapes/init/CinderscapeConfiguredFeatures.java#L201

It could be better to use `getIds().contains()` instead.

**Comment by ghost** [comment]
Sounds like a good idea, I'll push a hotfix in a sec
