### ISSUE TITLE
[1.16.3] Game crashes during launch

### ISSUE THREAD

**Issue by saltyseadoggo** [TerraformersMC/Cinderscapes#83]
I figure issues of this caliber are to be expected in an alpha, but I also figured that I would send the crash report.~
This crash report was gathered from a fresh installation with only Cinderscapes and the Fabric API in the _mods_ directory.
[crash-2020-10-18_12.22.59-client.txt](https://github.com/TerraformersMC/Cinderscapes/files/5398052/crash-2020-10-18_12.22.59-client.txt)

**Comment by coderbot16** [comment]
Looks like you need to update to a newer Fabric API. However, Cinderscapes should include a minimum version requirement instead of just crashing hard like this.

**Comment by saltyseadoggo** [comment]
Ah, very well. Thank you for clarifying.~

**Comment by coderbot16** [comment]
No problem!
