### ISSUE TITLE
#55 applies to Ghastly Ectoplasm

### ISSUE THREAD

**Issue by saltyseadoggo** [TerraformersMC/Cinderscapes#84]
Ghastly Ectoplasm has the same issues of hiding other Ghastly Ectoplasm behind its transparent areas, due to being semi-transparent itself, and thus not being applicable to the _CUTOUT_ render layer. I completely understand if this is impossible to fix, but I figured I would mention it due to the ugly effects it has on naturally occurring twilight vines. Making their textures opaque and moving it to the _CUTOUT_ layer would be an easy fix, but would lose the semi-transparency.
![2020-10-18_14 15 09](https://user-images.githubusercontent.com/69029346/96386170-cb8b7380-114d-11eb-9f0e-315ee22fa8e6.png)
![2020-10-18_14 15 12](https://user-images.githubusercontent.com/69029346/96386171-cd553700-114d-11eb-9083-810e8dccadf8.png)

**Comment by ghost** [comment]
I believe we made the ectoplasm simply cutout to solve the problem, so I'm pretty sure this issue is resolved. If not, that's how I've reimplemented it on the 1.17 branch.
