### ISSUE TITLE
Enhancement: The biome name "Quartz Canyon" is ill-fitting

### ISSUE THREAD

**Issue by saltyseadoggo** [TerraformersMC/Cinderscapes#87]
In my journeys across the Cinderscapes Nether, I can't help but notice that the Quartz Canyon biomes very seldomly form anything resembling canyons. The Nether's generation in general seldom forms anything like canyons due to its nature of having a roof. It isn't a big deal in the slightest, but I would like to suggest the alternative names *Quartz Cavern* and *Crystal Grotto*. The former is very similar to the current name and has the benefit of retaining its pseudo-alliteration. The latter is a bit further out there, but works in the fun word _grotto_ instead of the more on-the-nose _cavern_.~

**Comment by LudoCrypt** [comment]
Yeah, "Canyon" isn't a really fitting thing to have for what it is. Though grotto is a manmade cave, so I don't really see that fit either. I think it could be renamed to something like "Crystal Subterrane" but I'm not sure. I do like the idea of "Quartz Cavern" though!

**Comment by NeusFear** [comment]
I like that name a lot actually

**Comment by coderbot16** [comment]
How about "Crystal Cavern?"

**Comment by ghost** [comment]
I like Quartz Cavern or Crystal Cavern I think we'll probably end up changing it, but I'm going to wait until we actually add new biomes because that will also likely be a breaking change and I don't want to cause compatibility issues right now.

**Comment by coderbot16** [comment]
You can change the language file without changing the registry name, that would make the change non-breaking. So it would still have the original name in code but users would see the new name

**Comment by ghost** [comment]
Yeah we could probably do that temporarily, I would like to fully refactor it though eventually if we're going to be renaming it permanently

**Comment by ghost** [comment]
We're gonna go with Quartz Cavern I've got it changed in 1.17 dev
