### ISSUE TITLE
1.1.2 creative tab loading too fast?

### ISSUE THREAD

**Issue by Monster-Zer0** [TerraformersMC/Cinderscapes#91]
https://cdn.discordapp.com/attachments/750220836191076383/768232159566888960/Screen_Shot_2020-10-20_at_6.00.10_PM.png

and

https://media.discordapp.net/attachments/750220836191076383/768232567828643860/Screen_Shot_2020-10-20_at_6.01.45_PM.png

vanilla elements are not in creative screen when cinderscapes is loaded

v1.1.2
mc 1.16.3

**Comment by ghost** [comment]
Could you do some extra digging for us, this issue doesn't occur in most run environments meaning it's an interaction with another mod. Could you try removing everything except for Cinderscapes and then adding mods back in one by one until you find what the culprit is?

**Comment by ghost** [comment]
Nvm I'm also getting the same issue in a pack, I'll check it out

**Comment by ghost** [comment]
Something to do with Astromine is messing it up. I'm not sure why Astromine and Cinderscapes but that's what's happening

**Comment by dandin87** [comment]
For some reason CCA in the pack did not get updated and was v2.6, updated to 2.7.1 and the inventory is fine now. I do not think Cinderscapes had anything to do with it as I do not see CCA in cinderscapes.

**Comment by Disxconected** [comment]
i'm having this issue with the latest version of Cinderscapes for 1.16.3 and narrowed it down to an interaction with Curios api hopefully that can help you find the culprit in the code

**Comment by ghost** [comment]
@Disxconected are you sure it's Curios? There doesn't seem to be literally anything in their code that might trigger it.

**Comment by Disxconected** [comment]
with all other mods save the fabric api this issue remained i also tested just this and the fabric api and no issue 
disregard this is mistyped

**Comment by ghost** [comment]
Interesting

**Comment by Disxconected** [comment]
to clarify with just fabric, curios and this the issue remained and in the absence of curios the issue was gone. i brain farted when typing that last one

**Comment by Monster-Zer0** [comment]
I updated CCA and the problem no longer exists. I think that is the culprit
