### ISSUE TITLE
Game crashes when looking at the yellow ceiling quartz

### ISSUE THREAD

**Issue by defenestrationdude** [TerraformersMC/Cinderscapes#99]
The game consistently crashes if I look directly at the yellow coloured quartz while in the nether; I am currently unsure if this is a conflict with another mod I have such as HWYLA or not.

**Comment by ghost** [comment]
That's kind of odd, could we get a log for the crash?

**Comment by defenestrationdude** [comment]
[crash-2020-10-30_01.04.18-server.txt](https://github.com/TerraformersMC/Cinderscapes/files/5468442/crash-2020-10-30_01.04.18-server.txt)
This is the most recent crash in this manner I've had

**Comment by coderbot16** [comment]
The crash log seems to indicate that Repurposed Structures is crashing, and there's nothing in the stack trace that mentions Cinderscapes. Try reporting to https://github.com/TelepathicGrunt/RepurposedStructures-Fabric/issues instead?

**Comment by defenestrationdude** [comment]
It seems this was an issue with repurposed structures and trees do not float having a conflict; I'm not sure why it crashed specifically on looking at the quartz blocks but it is resolved at least.
